// Code generated by "stringer -type=ENV"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEV-0]
	_ = x[TEST-1]
	_ = x[PROD-2]
}

const _ENV_name = "DEVTESTPROD"

var _ENV_index = [...]uint8{0, 3, 7, 11}

func (i ENV) String() string {
	if i < 0 || i >= ENV(len(_ENV_index)-1) {
		return "ENV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ENV_name[_ENV_index[i]:_ENV_index[i+1]]
}
