AppName = 'github.com/Yazzyk/skillfulPenCMS'


[Logger]
Level = "debug"
Path = "logs/run.log"

[Server]
Port = 8080
Level = "error"


[Database]
Host = '127.0.0.1'
Port = 3306
User = 'root'
Password = ''
DBName = 'skillful_pen_cms'